/*JDBC不能一次执行多句 每个语句末尾请加上分号*/
CREATE DATABASE IF NOT EXISTS chat CHARACTER SET UTF8;

SET FOREIGN_KEY_CHECKS=0;
CREATE TABLE IF NOT EXISTS chat.basedata (
  `dataId` bigint(16) NOT NULL DEFAULT '0',
  `dataType` INTEGER(2) DEFAULT NULL,
  `dataContent` VARCHAR(6000) DEFAULT NULL,
  PRIMARY KEY (`dataId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

SET FOREIGN_KEY_CHECKS=0;
CREATE TABLE IF NOT EXISTS chat.msgdata (
  `_id` bigint(16) unsigned zerofill NOT NULL AUTO_INCREMENT,
  `FromUserId` INTEGER(10) DEFAULT NULL,
  `ToUserId` INTEGER(10) DEFAULT NULL,
  `CreateTime` bigint(16) DEFAULT NULL,
  `MsgType` INTEGER(2) DEFAULT NULL,
  `Content` VARCHAR(4096) DEFAULT '',
  `IsRead` INTEGER(2) DEFAULT '0',
  `OtherNote` VARCHAR(256) DEFAULT '',
  PRIMARY KEY (`_id`)
) ENGINE=InnoDB AUTO_INCREMENT=23 DEFAULT CHARSET=utf8;

SET FOREIGN_KEY_CHECKS=0;
CREATE TABLE IF NOT EXISTS chat.pushmsg (
  `_id` bigint(16) NOT NULL DEFAULT '-1',
  `CreateUser` INTEGER(10) DEFAULT NULL,
  `CreateTime` bigint(16) DEFAULT NULL,
  `PushTitle` VARCHAR(128) DEFAULT NULL,
  `pushContent` VARCHAR(4096) DEFAULT NULL,
  PRIMARY KEY (`_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

SET FOREIGN_KEY_CHECKS=0;
CREATE TABLE IF NOT EXISTS chat.pushuser (
  `_id` bigint(16) NOT NULL AUTO_INCREMENT,
  `CreateTime` bigint(16) DEFAULT NULL,
  `UserId` INTEGER(10) DEFAULT NULL,
  `PushId` bigint(16) DEFAULT NULL,
  PRIMARY KEY (`_id`)
) ENGINE=InnoDB AUTO_INCREMENT=1594 DEFAULT CHARSET=utf8;

SET FOREIGN_KEY_CHECKS=0;
CREATE TABLE IF NOT EXISTS chat.users (
  `_id` bigint(16) unsigned NOT NULL AUTO_INCREMENT,
  `UserName` VARCHAR(10) DEFAULT '',
  `PassWord` VARCHAR(10) DEFAULT '',
  `InLinear` INTEGER(2) DEFAULT '0',
  PRIMARY KEY (`_id`)
) ENGINE=InnoDB AUTO_INCREMENT=40102 DEFAULT CHARSET=utf8;